### PR TITLE
Resolves issue #8

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Resolves issue #8.

### CODE REVIEW

**Comment by peter279k** [comment]
@bosunski, this should be considered, too :).

**Comment by bosunski** [comment]
Thanks for noticing this.

@peter279k I probably forgot to add PHP 7.1 in the Travis file (Which I will do now and see the results). But the package is meant to be compatible with PHP 7.1, dropping support for PHP 7.1 will have to be in the next major release, say, `2.0`.

**Comment by peter279k** [comment]
@bosunski, thanks for your reply.

I just notice that these cached dependencies defined on `composer.lock` cannot be compatible with `PHP-7.1` version.

And you can look at detailed description on issue #8.

The final decision about PHP version support and that's up to you :). 

I'm happy to work on that if having any advanced pull request changes.

**Comment by bosunski** [comment]
Yea you're right! The `composer.lock` file shouldn't even be committed in the first place. I will remove and run some tests now.

**Comment by bosunski** [comment]
@peter279k check #12. It fixes failing tests in `PHP 7.1` and also removed the `composer.lock` file. Travis file has also being updated to include `PHP 7.1` for the tests.

**Comment by peter279k** [comment]
@bosunski, good. Thanks for your fix :).

**Pull request closed without merging**
